### ISSUE TITLE
Add GitHub Action to "redeploy" site

### ISSUE THREAD

**Issue by jwalton3141** [nationalarchives/DiAGRAM#46]
The frontend is hosted as a static site in an S3 bucket.

A GitHub workflow should be prepared to update the hosted site when changes to the frontend code are made in this repo.

Such a workflow _might_ look _something like_: 

```
name: Update deployed site

on: 
  push:
    paths:
      - app/**

jobs:

  push_to_env_matching_branch:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"

    strategy:
      matrix:
        config:
          - {branch: master, aws_region: eu-west-2 }

    steps:

      - uses: actions/checkout@v3
        if: ${{ contains(github.ref, matrix.config.branch) }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.config.aws_region }}
        if: ${{ contains(github.ref, matrix.config.branch) }}

     - name: Build static site 
       run: |
          cd app && npm run build

      - name: Update static site hosted in S3
        run: |
          aws s3 cp dist s3://${{ secrets.BUCKET_NAME }}/ --recursive
```

What I know needs checking / is incomplete in the above:

- Does the runner already have node and npm installed? or do these need installing before the site can be built?
- `aws s3 cp` _almost certainly_ isn't the best option here: it won't clear files in the bucket that have been removed from the site build, and it will be inefficient in files needlessly copying over identical files. Instead look into `aws s3 sync`. Is it possible to have `sync` remove files which are present in the bucket, but not in the Actions site-build? If not, do we have to do an `aws s3 rm` ?
